/*
  This file is generated by the LuaDist CMake build.
*/

#ifndef __ZMQ_PLATFORM_HPP_INCLUDED__
#define __ZMQ_PLATFORM_HPP_INCLUDED__

#define @ZMQ_PLATFORM@

#cmakedefine ZMQ_HAVE_IFADDRS 1
#cmakedefine ZMQ_HAVE_UIO 1
#cmakedefine ZMQ_HAVE_EVENTFD 1
#cmakedefine ZMQ_HAVE_OPENPGM 1
#cmakedefine ZMQ_HAVE_SOCK_CLOEXEC 1

#endif
